version: '3'

services:
  concourse-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: web
    depends_on: [concourse-db]
    restart: always
    ports:
      - 8080:8080
    environment:
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_VAULT_URL: https://vault:8200
      CONCOURSE_VAULT_AUTH_BACKEND: cert
      CONCOURSE_VAULT_CA_CERT: /vault-certs/vault-ca.crt
      CONCOURSE_VAULT_CLIENT_CERT: /vault-certs/concourse.crt
      CONCOURSE_VAULT_CLIENT_KEY: /vault-certs/concourse.key
    volumes:
      - ./vault-certs:/vault-certs
      - ./keys/web:/concourse-keys

  concourse-worker:
    image: concourse/concourse
    command: worker
    restart: always
    privileged: true
    depends_on: [concourse]
    volumes:
      - ./keys/worker:/concourse-keys
    links: [concourse]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_TSA_HOST: concourse:2222
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  vault:
    image: vault
    cap_add: [IPC_LOCK]
    restart: always
    ports:
      - 8200:8200
    environment:
      VAULT_CACERT: /vault/certs/vault-ca.crt
    volumes:
      - ./vault-certs:/vault/certs
      - ./vault-config:/vault/config
      - ./vault/file:/vault/file
    command: server -log-level=info
