FROM golang:1.11.2-alpine as build

# Build
RUN apk update && apk add -y git
RUN go get github.com/square/certstrap
RUN go build -o /usr/bin/certstrap github.com/square/certstrap

# Create a multi-stage build with the binary
FROM alpine

COPY --from=build /usr/bin/certstrap /usr/bin/certstrap

ENTRYPOINT ["/usr/bin/certstrap"]
